language: cpp

compiler:
  - gcc
  - clang

env:
  - TRAVIS_BUILD_TYPE=Debug
  - TRAVIS_BUILD_TYPE=Release

install:
 - sudo sh -c 'echo "deb http://www.icub.org/ubuntu precise contrib/science" > /etc/apt/sources.list.d/icub.list'
 - sudo add-apt-repository -y ppa:kalakris/cmake
 - sudo apt-get update
 - sudo apt-get install -qq libeigen3-dev libboost-system-dev libboost-thread-dev libboost-test-dev
 - sudo apt-get --force-yes install icub-common
 - sudo apt-get install cmake

before_script:
  - cd ..  
  # use superbuild for getting iDynTree dependencies
  - git clone https://github.com/robotology/codyco-superbuild
  - cd codyco-superbuild
  - mkdir build
  - cd build
  # using the YCM_EP_MAINTAINER_MODE variable to enable the subproject-dependees target
  - cmake -G"${TRAVIS_CMAKE_GENERATOR}" -DCODYCO_TRAVIS_CI:BOOL=ON -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DYCM_EP_MAINTAINER_MODE:BOOL=ON -DNON_INTERACTIVE_BUILD:BOOL=TRUE ..
  - make codyco-modules-dependees
  - export CMAKE_PREFIX_PATH=/home/travis/build/robotology-playground/codyco-superbuild/build/install
  - cd ../..
  # go back to codyco-modules
  - cd codyco-modules

script:
  - mkdir build
  - cd build
  - cmake -DCODYCO_TRAVIS_CI:BOOL=ON -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DNON_INTERACTIVE_BUILD:BOOL=TRUE ..
  - cmake --build . --config ${TRAVIS_BUILD_TYPE}

notifications:
  email:
    - pegua1@gmail.com
