language: cpp

compiler:
  - gcc
  - clang

env:
  - TRAVIS_BUILD_TYPE=Debug
  - TRAVIS_BUILD_TYPE=Release

install:
  - sudo sh -c 'echo "deb http://www.icub.org/ubuntu precise contrib/science" > /etc/apt/sources.list.d/icub.list'
  - sudo apt-get update
  - sudo apt-get --force-yes install icub-common libboost-system-dev libboost-thread-dev libtinyxml-dev

before_script:
 - cd ..
 - git clone https://github.com/robotology/codyco-superbuild.git
 - cd codyco-superbuild
 - git checkout new_wbi_ID
 #todo : change checkout of the codyco-modules in the codyco-superbuild to match the one of this commit

script:
  - mkdir build
  - cd build
  - cmake -DCODYCO_TRAVIS_CI:BOOL=ON -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DNON_INTERACTIVE_BUILD:BOOL=TRUE ..
  - cmake --build . --config ${TRAVIS_BUILD_TYPE}

notifications:
  email:
    - pegua1@gmail.com
